services:
  nextjs:
    build:
      context: .
      # Sélectionner le bon dockerfile avec les variables d'env correctes. 
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      SERVER_VPS1_IP : ${SERVER_VPS1_IP:?error}
      ARM_VPS1_API_KEY : ${ARM_VPS1_API_KEY:?error}
    ports :
      - 3000:3000
    networks:
      - production-network
    labels:
      # - traefik.http.routers.nextjs.rule=PathPrefix(`/`)
      - traefik.http.routers.nextjs.tls=true


networks:
  production-network:
    name: production-network
    external: true
